hydra:
  run:
    dir: "."
skip_for_run_all: True
simple_nvidia_smi_display: False
google_drive: True
save_models_to_google_drive: True
diffusion_model: "512x512_diffusion_uncond_finetune_008100"
use_secondary_model: True
diffusion_sampling_mode: 'ddim'
use_checkpoint: True
ViTB32: True
ViTB16: True
ViTL14: False
RN101: False
RN50: True
RN50x4: False
RN50x16: False
RN50x64: False
check_model_SHA: False
batch_name: 'TimeToDisco'
steps: 250
width_height:
  - 1280
  - 768
clip_guidance_scale: 5000
tv_scale: 0
range_scale: 150
sat_scale: 0
cutn_batches: 4
skip_augs: False
init_image: None
init_scale: 1000
skip_steps: 10
animation_mode: 'None'
video_init_path: "training.mp4"
extract_nth_frame: 2
video_init_seed_continuity: True
key_frames: True
max_frames: 10000
angle: "0:(0)"
zoom: "0: (1), 10: (1.05)"
translation_x: "0: (0)"
translation_y: "0: (0)"
translation_z: "0: (10.0)"
rotation_3d_x: "0: (0)"
rotation_3d_y: "0: (0)"
rotation_3d_z: "0: (0)"
midas_depth_model: "dpt_large"
midas_weight: 0.3
near_plane: 200
far_plane: 10000
fov: 40
padding_mode: 'border'
sampling_mode: 'bicubic'
turbo_mode: False
turbo_steps: "3"
frames_scale: 1500
frames_skip_steps: '60%'
vr_mode: False
vr_eye_angle: 0.5
vr_ipd: 5.0
intermediate_saves: 0
intermediates_in_subfolder: True
perlin_init: False
perlin_mode: 'mixed'
set_seed: 'random_seed'
eta: 0.8
clamp_grad: True
clamp_max: 0.05
cut_overview: "[12]*400+[4]*600"
cut_innercut: "[4]*400+[12]*600"
cut_ic_pow: 1
cut_icgray_p: "[0.2]*400+[0]*600"
display_rate: 50
n_batches: 50
resume_run: False
run_to_resume: 'latest'
resume_from_frame: 'latest'
retain_overwritten_frames: False
skip_video_for_run_all: True
folder: batch_name
run: latest_run
init_frame: 1
last_frame: final_frame
fps: 12